
ckbPath: #replace here with the full path where ckb binary located, e.g. D:/ckb #
nodePath: #replace here with ckb node's full path, e.g. D:/ckb/devNet #
chromedriverPath: ./chromedriver-v7.1.11-win32-x64/chromedriver.exe

